In [36]:
import pandas as pd

In [37]:
df=pd.read_csv("stock_data_50_records.csv")

In [38]:
df

          Date    Open    High     Low   Close    Volume
0   2026-01-02  101.09  103.37  100.08  102.04   89377.0
1   2026-01-05  101.05  101.99   99.91  100.58   88404.0
2   2026-01-06  102.41  103.15   99.47  101.36   94045.0
3   2026-01-07  105.35  108.05  103.53  106.87   72352.0
4   2026-01-08  105.13  109.88  104.24  107.49   79790.0
5   2026-01-09  104.91  108.22  103.42  107.07   81919.0
6   2026-01-12  107.95  109.49  104.84  106.57   45600.0
7   2026-01-13  109.53  111.44  107.88     NaN   69124.0
8   2026-01-14  108.89  111.08  107.60  109.85   67643.0
9   2026-01-15  110.07  114.76  109.21  112.32   80764.0
10  2026-01-16  109.43  111.85  108.13  108.77   49007.0
11  2026-01-19  108.79  109.79  106.87  108.72  450000.0
12  2026-01-20  109.43  110.92  105.67  107.52   96835.0
13  2026-01-21  106.18  107.28  102.64  104.09   77410.0
14  2026-01-22  103.28  106.28  102.27  105.21   84080.0
15  2026-01-23  102.47  106.05  101.45  105.48   80447.0
16  2026-01-26  100.84  102.72   99.25  101.00   48208.0
17  2026-01-27  101.61  105.43   99.76  103.92   96491.0
18  2026-01-28  100.18  101.80   98.35  101.20       NaN
19  2026-01-29   97.83   98.89   95.17   96.84   58589.0
20  2026-01-09  104.91  108.22  103.42  107.07   81919.0
21  2026-02-02  100.47  104.83   99.84  103.85   57453.0
22  2026-02-03  100.79  101.81  100.05  101.02   76212.0
23  2026-02-04   98.42  103.33   96.57  101.85   83525.0
24  2026-02-05   97.64  100.11   91.29   92.70   87202.0
25  2026-02-06   98.04  100.96   97.53   99.98   72635.0
26  2026-02-09   96.17   98.48   95.52   96.64   73828.0
27  2026-02-10   97.05   99.07   95.25   96.75  620000.0
28  2026-02-11   96.17   97.63   95.66   96.65   43420.0
29  2026-02-12   95.84   97.80   91.42   92.16   71216.0
30  2026-02-13   94.96   96.20   93.50   94.82   40301.0
31  2026-02-16   98.49  101.26   96.95   99.50   85236.0
32  2026-02-17   98.67     NaN   97.19  101.93   89758.0
33  2026-02-18   96.96   98.53   95.38   96.22   92322.0
34  2026-02-19   98.64   99.32   95.75   97.32   40699.0
35  2026-01-22  103.28  106.28  102.27  105.21   84080.0
36  2026-02-23   97.22  100.49   96.23   99.35   98483.0
37  2026-02-24   93.89   95.72   92.27   94.85   40190.0
38  2026-02-25   91.70   92.28   89.47   90.94   50492.0
39  2026-02-26   92.26   95.27   90.49   93.59   90132.0
40  2026-02-27   93.79   96.14   92.30   94.28   75743.0
41  2026-03-02   94.30   97.07   92.95   96.54  850000.0
42  2026-03-03   94.29   95.81   92.55   93.19   90336.0
43  2026-03-04   93.95   94.90   92.54   93.59   92479.0
44  2026-03-05     NaN   93.27   90.10   91.00   59778.0
45  2026-03-06   90.39   91.24   86.89   87.76   97471.0
46  2026-03-09   89.76   92.53   87.80   90.65   66641.0
47  2026-02-06   98.04  100.96   97.53   99.98   72635.0
48  2026-03-11   92.68   95.36   90.84   92.99   72745.0
49  2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Open    49 non-null     float64
 2   High    49 non-null     float64
 3   Low     50 non-null     float64
 4   Close   49 non-null     float64
 5   Volume  49 non-null     float64
dtypes: float64(5), object(1)
memory usage: 2.5+ KB

In [40]:
df.head()

         Date    Open    High     Low   Close   Volume
0  2026-01-02  101.09  103.37  100.08  102.04  89377.0
1  2026-01-05  101.05  101.99   99.91  100.58  88404.0
2  2026-01-06  102.41  103.15   99.47  101.36  94045.0
3  2026-01-07  105.35  108.05  103.53  106.87  72352.0
4  2026-01-08  105.13  109.88  104.24  107.49  79790.0

In [41]:
df.tail()

          Date   Open    High    Low  Close   Volume
45  2026-03-06  90.39   91.24  86.89  87.76  97471.0
46  2026-03-09  89.76   92.53  87.80  90.65  66641.0
47  2026-02-06  98.04  100.96  97.53  99.98  72635.0
48  2026-03-11  92.68   95.36  90.84  92.99  72745.0
49  2026-03-12  89.71   90.49  88.09  89.54  95006.0

In [42]:
df["Date"]=pd.to_datetime(df["Date"])
df.dtypes

Date      datetime64[ns]
Open             float64
High             float64
Low              float64
Close            float64
Volume           float64
dtype: object

In [43]:
df.isnull().sum()

Date      0
Open      1
High      1
Low       0
Close     1
Volume    1
dtype: int64

In [44]:
df.dropna()

         Date    Open    High     Low   Close    Volume
0  2026-01-02  101.09  103.37  100.08  102.04   89377.0
1  2026-01-05  101.05  101.99   99.91  100.58   88404.0
2  2026-01-06  102.41  103.15   99.47  101.36   94045.0
3  2026-01-07  105.35  108.05  103.53  106.87   72352.0
4  2026-01-08  105.13  109.88  104.24  107.49   79790.0
5  2026-01-09  104.91  108.22  103.42  107.07   81919.0
6  2026-01-12  107.95  109.49  104.84  106.57   45600.0
8  2026-01-14  108.89  111.08  107.60  109.85   67643.0
9  2026-01-15  110.07  114.76  109.21  112.32   80764.0
10 2026-01-16  109.43  111.85  108.13  108.77   49007.0
11 2026-01-19  108.79  109.79  106.87  108.72  450000.0
12 2026-01-20  109.43  110.92  105.67  107.52   96835.0
13 2026-01-21  106.18  107.28  102.64  104.09   77410.0
14 2026-01-22  103.28  106.28  102.27  105.21   84080.0
15 2026-01-23  102.47  106.05  101.45  105.48   80447.0
16 2026-01-26  100.84  102.72   99.25  101.00   48208.0
17 2026-01-27  101.61  105.43   99.76  103.92   96491.0
19 2026-01-29   97.83   98.89   95.17   96.84   58589.0
20 2026-01-09  104.91  108.22  103.42  107.07   81919.0
21 2026-02-02  100.47  104.83   99.84  103.85   57453.0
22 2026-02-03  100.79  101.81  100.05  101.02   76212.0
23 2026-02-04   98.42  103.33   96.57  101.85   83525.0
24 2026-02-05   97.64  100.11   91.29   92.70   87202.0
25 2026-02-06   98.04  100.96   97.53   99.98   72635.0
26 2026-02-09   96.17   98.48   95.52   96.64   73828.0
27 2026-02-10   97.05   99.07   95.25   96.75  620000.0
28 2026-02-11   96.17   97.63   95.66   96.65   43420.0
29 2026-02-12   95.84   97.80   91.42   92.16   71216.0
30 2026-02-13   94.96   96.20   93.50   94.82   40301.0
31 2026-02-16   98.49  101.26   96.95   99.50   85236.0
33 2026-02-18   96.96   98.53   95.38   96.22   92322.0
34 2026-02-19   98.64   99.32   95.75   97.32   40699.0
35 2026-01-22  103.28  106.28  102.27  105.21   84080.0
36 2026-02-23   97.22  100.49   96.23   99.35   98483.0
37 2026-02-24   93.89   95.72   92.27   94.85   40190.0
38 2026-02-25   91.70   92.28   89.47   90.94   50492.0
39 2026-02-26   92.26   95.27   90.49   93.59   90132.0
40 2026-02-27   93.79   96.14   92.30   94.28   75743.0
41 2026-03-02   94.30   97.07   92.95   96.54  850000.0
42 2026-03-03   94.29   95.81   92.55   93.19   90336.0
43 2026-03-04   93.95   94.90   92.54   93.59   92479.0
45 2026-03-06   90.39   91.24   86.89   87.76   97471.0
46 2026-03-09   89.76   92.53   87.80   90.65   66641.0
47 2026-02-06   98.04  100.96   97.53   99.98   72635.0
48 2026-03-11   92.68   95.36   90.84   92.99   72745.0
49 2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [45]:
df.duplicated().sum()

np.int64(3)

In [46]:
df=df.drop_duplicates()

In [47]:
df

         Date    Open    High     Low   Close    Volume
0  2026-01-02  101.09  103.37  100.08  102.04   89377.0
1  2026-01-05  101.05  101.99   99.91  100.58   88404.0
2  2026-01-06  102.41  103.15   99.47  101.36   94045.0
3  2026-01-07  105.35  108.05  103.53  106.87   72352.0
4  2026-01-08  105.13  109.88  104.24  107.49   79790.0
5  2026-01-09  104.91  108.22  103.42  107.07   81919.0
6  2026-01-12  107.95  109.49  104.84  106.57   45600.0
7  2026-01-13  109.53  111.44  107.88     NaN   69124.0
8  2026-01-14  108.89  111.08  107.60  109.85   67643.0
9  2026-01-15  110.07  114.76  109.21  112.32   80764.0
10 2026-01-16  109.43  111.85  108.13  108.77   49007.0
11 2026-01-19  108.79  109.79  106.87  108.72  450000.0
12 2026-01-20  109.43  110.92  105.67  107.52   96835.0
13 2026-01-21  106.18  107.28  102.64  104.09   77410.0
14 2026-01-22  103.28  106.28  102.27  105.21   84080.0
15 2026-01-23  102.47  106.05  101.45  105.48   80447.0
16 2026-01-26  100.84  102.72   99.25  101.00   48208.0
17 2026-01-27  101.61  105.43   99.76  103.92   96491.0
18 2026-01-28  100.18  101.80   98.35  101.20       NaN
19 2026-01-29   97.83   98.89   95.17   96.84   58589.0
21 2026-02-02  100.47  104.83   99.84  103.85   57453.0
22 2026-02-03  100.79  101.81  100.05  101.02   76212.0
23 2026-02-04   98.42  103.33   96.57  101.85   83525.0
24 2026-02-05   97.64  100.11   91.29   92.70   87202.0
25 2026-02-06   98.04  100.96   97.53   99.98   72635.0
26 2026-02-09   96.17   98.48   95.52   96.64   73828.0
27 2026-02-10   97.05   99.07   95.25   96.75  620000.0
28 2026-02-11   96.17   97.63   95.66   96.65   43420.0
29 2026-02-12   95.84   97.80   91.42   92.16   71216.0
30 2026-02-13   94.96   96.20   93.50   94.82   40301.0
31 2026-02-16   98.49  101.26   96.95   99.50   85236.0
32 2026-02-17   98.67     NaN   97.19  101.93   89758.0
33 2026-02-18   96.96   98.53   95.38   96.22   92322.0
34 2026-02-19   98.64   99.32   95.75   97.32   40699.0
36 2026-02-23   97.22  100.49   96.23   99.35   98483.0
37 2026-02-24   93.89   95.72   92.27   94.85   40190.0
38 2026-02-25   91.70   92.28   89.47   90.94   50492.0
39 2026-02-26   92.26   95.27   90.49   93.59   90132.0
40 2026-02-27   93.79   96.14   92.30   94.28   75743.0
41 2026-03-02   94.30   97.07   92.95   96.54  850000.0
42 2026-03-03   94.29   95.81   92.55   93.19   90336.0
43 2026-03-04   93.95   94.90   92.54   93.59   92479.0
44 2026-03-05     NaN   93.27   90.10   91.00   59778.0
45 2026-03-06   90.39   91.24   86.89   87.76   97471.0
46 2026-03-09   89.76   92.53   87.80   90.65   66641.0
48 2026-03-11   92.68   95.36   90.84   92.99   72745.0
49 2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [48]:
df.isnull().sum()

Date      0
Open      1
High      1
Low       0
Close     1
Volume    1
dtype: int64

In [57]:
df["Price_Delta"] = df["Close"] - df["Open"]
df

C:\Users\sheikh safana ilyas\AppData\Local\Temp\ipykernel_30860\4257002924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price_Delta"] = df["Close"] - df["Open"]

,Date,Open,High,Low,Close,Volume,Price_Delta,Daily_return,Volume_MA_7
0,2026-01-02,101.09,103.37,100.08,102.04,89377.0,0.95,NaN,NaN
1,2026-01-05,101.05,101.99,99.91,100.58,88404.0,-0.47,-1.430811,NaN
2,2026-01-06,102.41,103.15,99.47,101.36,94045.0,-1.05,0.775502,NaN
3,2026-01-07,105.35,108.05,103.53,106.87,72352.0,1.52,5.436069,NaN
4,2026-01-08,105.13,109.88,104.24,107.49,79790.0,2.36,0.580144,NaN
5,2026-01-09,104.91,108.22,103.42,107.07,81919.0,2.16,-0.390734,NaN
6,2026-01-12,107.95,109.49,104.84,106.57,45600.0,-1.38,-0.466984,78783.857143
7,2026-01-13,109.53,111.44,107.88,NaN,69124.0,NaN,0.000000,75890.571429
8,2026-01-14,108.89,111.08,107.60,109.85,67643.0,0.96,3.077789,72924.714286
9,2026-01-15,110.07,114.76,109.21,112.32,80764.0,2.25,2.248521,71027.428571
10,2026-01-16,109.43,111.85,108.13,108.77,49007.0,-0.66,-3.160613,67692.428571
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,-0.07,-0.045969,120579.571429
12,2026-01-20,109.43,110.92,105.67,107.52,96835.0,-1.91,-1.103753,122710.428571
13,2026-01-21,106.18,107.28,102.64,104.09,77410.0,-2.09,-3.190104,127254.714286
14,2026-01-22,103.28,106.28,102.27,105.21,84080.0,1.93,1.075992,129391.285714
15,2026-01-23,102.47,106.05,101.45,105.48,80447.0,3.01,0.256630,131220.428571
16,2026-01-26,100.84,102.72,99.25,101.00,48208.0,0.16,-4.247251,126569.571429
17,2026-01-27,101.61,105.43,99.76,103.92,96491.0,2.31,2.891089,133353.000000
18,2026-01-28,100.18,101.80,98.35,101.20,NaN,1.02,-2.617398,NaN
19,2026-01-29,97.83,98.89,95.17,96.84,58589.0,-0.99,-4.308300,NaN
21,2026-02-02,100.47,104.83,99.84,103.85,57453.0,3.38,7.238744,NaN
22,2026-02-03,100.79,101.81,100.05,101.02,76212.0,0.23,-2.725084,NaN
23,2026-02-04,98.42,103.33,96.57,101.85,83525.0,3.43,0.821619,NaN
24,2026-02-05,97.64,100.11,91.29,92.70,87202.0,-4.94,-8.983800,NaN
25,2026-02-06,98.04,100.96,97.53,99.98,72635.0,1.94,7.853290,NaN
26,2026-02-09,96.17,98.48,95.52,96.64,73828.0,0.47,-3.340668,72777.714286
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,-0.30,0.113825,152979.285714
28,2026-02-11,96.17,97.63,95.66,96.65,43420.0,0.48,-0.103359,150974.571429
29,2026-02-12,95.84,97.80,91.42,92.16,71216.0,-3.68,-4.645629,150260.857143
30,2026-02-13,94.96,96.20,93.50,94.82,40301.0,-0.14,2.886285,144086.000000
31,2026-02-16,98.49,101.26,96.95,99.50,85236.0,1.01,4.935668,143805.142857
32,2026-02-17,98.67,NaN,97.19,101.93,89758.0,3.26,2.442211,146251.285714
33,2026-02-18,96.96,98.53,95.38,96.22,92322.0,-0.74,-5.601884,148893.285714
34,2026-02-19,98.64,99.32,95.75,97.32,40699.0,-1.32,1.143213,66136.000000
36,2026-02-23,97.22,100.49,96.23,99.35,98483.0,2.13,2.085902,74002.142857
37,2026-02-24,93.89,95.72,92.27,94.85,40190.0,0.96,-4.529441,69569.857143
38,2026-02-25,91.70,92.28,89.47,90.94,50492.0,-0.76,-4.122298,71025.714286
39,2026-02-26,92.26,95.27,90.49,93.59,90132.0,1.33,2.914009,71725.142857
40,2026-02-27,93.79,96.14,92.30,94.28,75743.0,0.49,0.737258,69723.000000
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,2.24,2.397115,177962.714286
42,2026-03-03,94.29,95.81,92.55,93.19,90336.0,-1.10,-3.470064,185053.714286
43,2026-03-04,93.95,94.90,92.54,93.59,92479.0,-0.36,0.429231,184196.000000
44,2026-03-05,NaN,93.27,90.10,91.00,59778.0,NaN,-2.767390,186994.285714
45,2026-03-06,90.39,91.24,86.89,87.76,97471.0,-2.63,-3.560440,193705.571429
46,2026-03-09,89.76,92.53,87.80,90.65,66641.0,0.89,3.293072,190349.714286
48,2026-03-11,92.68,95.36,90.84,92.99,72745.0,0.31,2.581357,189921.428571
49,2026-03-12,89.71,90.49,88.09,89.54,95006.0,-0.17,-3.710076,82065.142857

In [58]:
df["Daily_return"] = df["Close"].pct_change() * 100

C:\Users\sheikh safana ilyas\AppData\Local\Temp\ipykernel_30860\957036541.py:1: FutureWarning: The default fill_method='pad' in Series.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df["Daily_return"] = df["Close"].pct_change() * 100
C:\Users\sheikh safana ilyas\AppData\Local\Temp\ipykernel_30860\957036541.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Daily_return"] = df["Close"].pct_change() * 100

In [59]:
df["Volume_MA_7"] = df["Volume"].rolling(7).mean()

C:\Users\sheikh safana ilyas\AppData\Local\Temp\ipykernel_30860\3204605728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Volume_MA_7"] = df["Volume"].rolling(7).mean()

In [52]:
volume_mean = df["Volume"].mean()
volume_std = df["Volume"].std()
volume_threshold = volume_mean + (2 * volume_std)

In [53]:
anomalies = df[df["Volume"] > volume_threshold]
print(anomalies)

         Date    Open    High     Low   Close    Volume  Price_Delta  \
11 2026-01-19  108.79  109.79  106.87  108.72  450000.0        -0.07
27 2026-02-10   97.05   99.07   95.25   96.75  620000.0        -0.30
41 2026-03-02   94.30   97.07   92.95   96.54  850000.0         2.24

    Daily_return    Volume_MA_7
11     -0.045969  120579.571429
27      0.113825  152979.285714
41      2.397115  177962.714286

In [54]:
mean_return = df["Daily_return"].mean()
print("Mean Return:", mean_return)

Mean Return: -0.224076393360342

In [55]:
variance_return = df["Daily_return"].var()
print("Variance Return:", variance_return)

Variance Return: 12.155846027368774

In [56]:
std_return = df["Daily_return"].std()
print("Std Return:", std_return)

Std Return: 3.486523487281962

In [34]:
df

,Date,Open,High,Low,Close,Volume,Price_Date,Daily_return,Volume_MA_7
0,2026-01-02,101.09,103.37,100.08,102.04,89377.0,0.95,NaN,NaN
1,2026-01-05,101.05,101.99,99.91,100.58,88404.0,-0.47,-1.430811,NaN
2,2026-01-06,102.41,103.15,99.47,101.36,94045.0,-1.05,0.775502,NaN
3,2026-01-07,105.35,108.05,103.53,106.87,72352.0,1.52,5.436069,NaN
4,2026-01-08,105.13,109.88,104.24,107.49,79790.0,2.36,0.580144,NaN
5,2026-01-09,104.91,108.22,103.42,107.07,81919.0,2.16,-0.390734,NaN
6,2026-01-12,107.95,109.49,104.84,106.57,45600.0,-1.38,-0.466984,78783.857143
7,2026-01-13,109.53,111.44,107.88,NaN,69124.0,NaN,0.000000,75890.571429
8,2026-01-14,108.89,111.08,107.60,109.85,67643.0,0.96,3.077789,72924.714286
9,2026-01-15,110.07,114.76,109.21,112.32,80764.0,2.25,2.248521,71027.428571
10,2026-01-16,109.43,111.85,108.13,108.77,49007.0,-0.66,-3.160613,67692.428571
11,2026-01-19,108.79,109.79,106.87,108.72,450000.0,-0.07,-0.045969,120579.571429
12,2026-01-20,109.43,110.92,105.67,107.52,96835.0,-1.91,-1.103753,122710.428571
13,2026-01-21,106.18,107.28,102.64,104.09,77410.0,-2.09,-3.190104,127254.714286
14,2026-01-22,103.28,106.28,102.27,105.21,84080.0,1.93,1.075992,129391.285714
15,2026-01-23,102.47,106.05,101.45,105.48,80447.0,3.01,0.256630,131220.428571
16,2026-01-26,100.84,102.72,99.25,101.00,48208.0,0.16,-4.247251,126569.571429
17,2026-01-27,101.61,105.43,99.76,103.92,96491.0,2.31,2.891089,133353.000000
18,2026-01-28,100.18,101.80,98.35,101.20,NaN,1.02,-2.617398,NaN
19,2026-01-29,97.83,98.89,95.17,96.84,58589.0,-0.99,-4.308300,NaN
21,2026-02-02,100.47,104.83,99.84,103.85,57453.0,3.38,7.238744,NaN
22,2026-02-03,100.79,101.81,100.05,101.02,76212.0,0.23,-2.725084,NaN
23,2026-02-04,98.42,103.33,96.57,101.85,83525.0,3.43,0.821619,NaN
24,2026-02-05,97.64,100.11,91.29,92.70,87202.0,-4.94,-8.983800,NaN
25,2026-02-06,98.04,100.96,97.53,99.98,72635.0,1.94,7.853290,NaN
26,2026-02-09,96.17,98.48,95.52,96.64,73828.0,0.47,-3.340668,72777.714286
27,2026-02-10,97.05,99.07,95.25,96.75,620000.0,-0.30,0.113825,152979.285714
28,2026-02-11,96.17,97.63,95.66,96.65,43420.0,0.48,-0.103359,150974.571429
29,2026-02-12,95.84,97.80,91.42,92.16,71216.0,-3.68,-4.645629,150260.857143
30,2026-02-13,94.96,96.20,93.50,94.82,40301.0,-0.14,2.886285,144086.000000
31,2026-02-16,98.49,101.26,96.95,99.50,85236.0,1.01,4.935668,143805.142857
32,2026-02-17,98.67,NaN,97.19,101.93,89758.0,3.26,2.442211,146251.285714
33,2026-02-18,96.96,98.53,95.38,96.22,92322.0,-0.74,-5.601884,148893.285714
34,2026-02-19,98.64,99.32,95.75,97.32,40699.0,-1.32,1.143213,66136.000000
36,2026-02-23,97.22,100.49,96.23,99.35,98483.0,2.13,2.085902,74002.142857
37,2026-02-24,93.89,95.72,92.27,94.85,40190.0,0.96,-4.529441,69569.857143
38,2026-02-25,91.70,92.28,89.47,90.94,50492.0,-0.76,-4.122298,71025.714286
39,2026-02-26,92.26,95.27,90.49,93.59,90132.0,1.33,2.914009,71725.142857
40,2026-02-27,93.79,96.14,92.30,94.28,75743.0,0.49,0.737258,69723.000000
41,2026-03-02,94.30,97.07,92.95,96.54,850000.0,2.24,2.397115,177962.714286
42,2026-03-03,94.29,95.81,92.55,93.19,90336.0,-1.10,-3.470064,185053.714286
43,2026-03-04,93.95,94.90,92.54,93.59,92479.0,-0.36,0.429231,184196.000000
44,2026-03-05,NaN,93.27,90.10,91.00,59778.0,NaN,-2.767390,186994.285714
45,2026-03-06,90.39,91.24,86.89,87.76,97471.0,-2.63,-3.560440,193705.571429
46,2026-03-09,89.76,92.53,87.80,90.65,66641.0,0.89,3.293072,190349.714286
48,2026-03-11,92.68,95.36,90.84,92.99,72745.0,0.31,2.581357,189921.428571
49,2026-03-12,89.71,90.49,88.09,89.54,95006.0,-0.17,-3.710076,82065.142857