In [24]:
import pandas as pd

In [25]:
df=pd.read_csv("sales_table.csv")

In [26]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0
5,1006,furniture,tables,corporate,9428.0,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,NaN,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.0,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.0,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.0,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.0,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.0,-178.0,18.0
12,1013,technology,phones,corporate,6425.0,1864.0,7.0
13,1014,furniture,tables,consumer,1250.0,2208.0,8.0
14,1015,technology,phones,consumer,4314.0,-87.0,13.0
15,1016,technology,phones,Consumer,6477.0,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.0,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.0,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.0,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.0,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.0,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.0,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.0,NaN,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.0,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.0,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.0,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.0,NaN,6.0
27,1028,furniture,tables,Consumer,NaN,NaN,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.0,529.0,18.0
29,1030,office supplies,binders,corporate,2376.0,2292.0,NaN
30,1031,technology,phones,corporate,6073.0,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.0,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.0,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.0,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.0,-498.0,20.0
35,1036,technology,phones,Consumer,819.0,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.0,486.0,19.0
37,1038,office supplies,binders,consumer,8462.0,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.0,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.0,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.0,2593.0,7.0
41,1042,furniture,tables,home office,7037.0,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,NaN,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.0,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.0,-471.0,3.0
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,NaN
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [27]:
df.tail()

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
45,1046,furniture,tables,corporate,1464.0,437.0,3.0
46,1047,office supplies,binders,home office,1660.0,1605.0,NaN
47,1048,technology,phones,corporate,8453.0,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.0,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.0,279.0,4.0

In [28]:
df.head()

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.0,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.0,2516.0,4.0
2,1003,furniture,tables,corporate,9435.0,-144.0,19.0
3,1004,office supplies,storage,consumer,988.0,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.0,1798.0,7.0

In [29]:
df.describe()

         Order ID        Sales       Profit   Quantity
count    50.00000    47.000000    47.000000  47.000000
mean   1025.50000  5351.063830  1139.744681  10.978723
std      14.57738  2962.622431  1145.804435   5.612445
min    1001.00000   819.000000  -498.000000   1.000000
25%    1013.25000  2684.500000   -23.500000   7.000000
50%    1025.50000  6014.000000  1143.000000  11.000000
75%    1037.75000  7726.000000  2229.500000  16.000000
max    1050.00000  9855.000000  2971.000000  20.000000

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      50 non-null     int64
 1   Category      50 non-null     object
 2   Sub-Category  50 non-null     object
 3   Segment       50 non-null     object
 4   Sales         47 non-null     float64
 5   Profit        47 non-null     float64
 6   Quantity      47 non-null     float64
dtypes: float64(3), int64(1), object(3)
memory usage: 2.9+ KB

In [31]:
df.isnull()

    Order ID  Category  Sub-Category  Segment  Sales  Profit  Quantity
0      False     False         False    False  False   False     False
1      False     False         False    False  False   False     False
2      False     False         False    False  False   False     False
3      False     False         False    False  False   False      True
4      False     False         False    False  False   False     False
5      False     False         False    False  False   False     False
6      False     False         False    False   True   False     False
7      False     False         False    False  False   False     False
8      False     False         False    False  False   False     False
9      False     False         False    False  False   False     False
10     False     False         False    False  False   False     False
11     False     False         False    False  False   False     False
12     False     False         False    False  False   False     False
13     False     False         False    False  False   False     False
14     False     False         False    False  False   False     False
15     False     False         False    False  False   False     False
16     False     False         False    False  False   False     False
17     False     False         False    False  False   False     False
18     False     False         False    False  False   False     False
19     False     False         False    False  False   False     False
20     False     False         False    False  False   False     False
21     False     False         False    False  False   False     False
22     False     False         False    False  False    True     False
23     False     False         False    False  False   False     False
24     False     False         False    False  False   False     False
25     False     False         False    False  False   False     False
26     False     False         False    False  False    True     False
27     False     False         False    False   True    True     False
28     False     False         False    False  False   False     False
29     False     False         False    False  False   False      True
30     False     False         False    False  False   False     False
31     False     False         False    False  False   False     False
32     False     False         False    False  False   False     False
33     False     False         False    False  False   False     False
34     False     False         False    False  False   False     False
35     False     False         False    False  False   False     False
36     False     False         False    False  False   False     False
37     False     False         False    False  False   False     False
38     False     False         False    False  False   False     False
39     False     False         False    False  False   False     False
40     False     False         False    False  False   False     False
41     False     False         False    False  False   False     False
42     False     False         False    False   True   False     False
43     False     False         False    False  False   False     False
44     False     False         False    False  False   False     False
45     False     False         False    False  False   False     False
46     False     False         False    False  False   False      True
47     False     False         False    False  False   False     False
48     False     False         False    False  False   False     False
49     False     False         False    False  False   False     False

In [32]:
df.isnull().sum()

Order ID        0
Category        0
Sub-Category    0
Segment         0
Sales           3
Profit          3
Quantity        3
dtype: int64

In [33]:
df["Profit"].bfill()

0     2537.0
1     2516.0
2     -144.0
3     -117.0
4     1798.0
5     1218.0
6     2815.0
7      893.0
8      -82.0
9     2971.0
10    2488.0
11    -178.0
12    1864.0
13    2208.0
14     -87.0
15     166.0
16    2374.0
17    1687.0
18     605.0
19    2952.0
20    1143.0
21    2440.0
22     510.0
23     510.0
24    1890.0
25    1587.0
26     529.0
27     529.0
28     529.0
29    2292.0
30     -44.0
31    -487.0
32     -65.0
33     126.0
34    -498.0
35     -42.0
36     486.0
37    2842.0
38    2202.0
39    1661.0
40    2593.0
41    2251.0
42      -5.0
43    -414.0
44    -471.0
45     437.0
46    1605.0
47     377.0
48    1860.0
49     279.0
Name: Profit, dtype: float64

In [34]:
df['Sales']=df['Sales'].fillna(df['Sales'].mean())

In [35]:
df['Profit']=df['Profit'].fillna(df['Profit'].median())

In [38]:
df['Quantity']=df['Quantity'].fillna(df['Quantity'].mode())

In [39]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.0
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.0
3,1004,office supplies,storage,consumer,988.00000,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.0
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.0
12,1013,technology,phones,corporate,6425.00000,1864.0,7.0
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.0
14,1015,technology,phones,consumer,4314.00000,-87.0,13.0
15,1016,technology,phones,Consumer,6477.00000,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.0
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.0
29,1030,office supplies,binders,corporate,2376.00000,2292.0,NaN
30,1031,technology,phones,corporate,6073.00000,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.0
35,1036,technology,phones,Consumer,819.00000,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.0
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.0
41,1042,furniture,tables,home office,7037.00000,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.0
45,1046,furniture,tables,corporate,1464.00000,437.0,3.0
46,1047,office supplies,binders,home office,1660.00000,1605.0,NaN
47,1048,technology,phones,corporate,8453.00000,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.0

In [37]:
df.duplicated().sum()

np.int64(0)

In [40]:
df['Sales']=df['Sales'].fillna(df['Sales'].mean())

In [58]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [41]:
df['Sales']=df['Sales'].fillna(df['Sales'].median())

In [59]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [ ]:
df['Sales']=df['Sales'].fillna(df['Sales'].mode())

In [42]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.0
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.0
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.0
3,1004,office supplies,storage,consumer,988.00000,-117.0,NaN
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.0
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.0
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.0
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.0
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.0
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.0
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.0
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.0
12,1013,technology,phones,corporate,6425.00000,1864.0,7.0
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.0
14,1015,technology,phones,consumer,4314.00000,-87.0,13.0
15,1016,technology,phones,Consumer,6477.00000,166.0,12.0
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.0
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.0
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.0
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.0
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.0
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.0
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.0
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.0
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.0
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.0
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.0
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.0
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.0
29,1030,office supplies,binders,corporate,2376.00000,2292.0,NaN
30,1031,technology,phones,corporate,6073.00000,-44.0,10.0
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.0
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.0
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.0
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.0
35,1036,technology,phones,Consumer,819.00000,-42.0,12.0
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.0
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.0
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.0
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.0
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.0
41,1042,furniture,tables,home office,7037.00000,2251.0,12.0
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.0
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.0
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.0
45,1046,furniture,tables,corporate,1464.00000,437.0,3.0
46,1047,office supplies,binders,home office,1660.00000,1605.0,NaN
47,1048,technology,phones,corporate,8453.00000,377.0,18.0
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.0
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.0

In [54]:
df['Profit']=df['Profit'].fillna(df['Profit'].mean())

In [55]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [44]:
df['Profit']=df['Profit'].fillna(df['Profit'].median())

In [56]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [45]:
df['Profit']=df['Profit'].fillna(df['Profit'].mode())

In [57]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [47]:
df['Quantity']=df['Quantity'].fillna(df['Quantity'].mean())

In [51]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [48]:
df['Quantity']=df['Quantity'].fillna(df['Quantity'].median())

In [52]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [49]:
df['Quantity']=df['Quantity'].fillna(df['Quantity'].mode())

In [53]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,furniture,tables,consumer,909.00000,2537.0,9.000000
1,1002,FURNITURE,CHAIRS,CORPORATE,2786.00000,2516.0,4.000000
2,1003,furniture,tables,corporate,9435.00000,-144.0,19.000000
3,1004,office supplies,storage,consumer,988.00000,-117.0,10.978723
4,1005,FURNITURE,CHAIRS,HOME OFFICE,934.00000,1798.0,7.000000
5,1006,furniture,tables,corporate,9428.00000,1218.0,8.000000
6,1007,office supplies,storage,HOME OFFICE,5351.06383,2815.0,1.000000
7,1008,FURNITURE,CHAIRS,corporate,7424.00000,893.0,9.000000
8,1009,FURNITURE,CHAIRS,CORPORATE,6014.00000,-82.0,3.000000
9,1010,office supplies,storage,consumer,6381.00000,2971.0,12.000000
10,1011,TECHNOLOGY,ACCESSORIES,home office,1211.00000,2488.0,15.000000
11,1012,TECHNOLOGY,ACCESSORIES,consumer,6701.00000,-178.0,18.000000
12,1013,technology,phones,corporate,6425.00000,1864.0,7.000000
13,1014,furniture,tables,consumer,1250.00000,2208.0,8.000000
14,1015,technology,phones,consumer,4314.00000,-87.0,13.000000
15,1016,technology,phones,Consumer,6477.00000,166.0,12.000000
16,1017,technology,phones,CORPORATE,4874.00000,2374.0,3.000000
17,1018,TECHNOLOGY,ACCESSORIES,corporate,3303.00000,1687.0,8.000000
18,1019,FURNITURE,CHAIRS,Consumer,6716.00000,605.0,18.000000
19,1020,FURNITURE,CHAIRS,corporate,5813.00000,2952.0,2.000000
20,1021,FURNITURE,CHAIRS,consumer,5668.00000,1143.0,9.000000
21,1022,office supplies,binders,CORPORATE,9792.00000,2440.0,11.000000
22,1023,FURNITURE,CHAIRS,corporate,8679.00000,1143.0,15.000000
23,1024,FURNITURE,CHAIRS,home office,2787.00000,510.0,18.000000
24,1025,TECHNOLOGY,ACCESSORIES,home office,7519.00000,1890.0,13.000000
25,1026,technology,phones,CORPORATE,2766.00000,1587.0,16.000000
26,1027,office supplies,binders,consumer,2296.00000,1143.0,6.000000
27,1028,furniture,tables,Consumer,5351.06383,1143.0,13.000000
28,1029,TECHNOLOGY,ACCESSORIES,Consumer,9169.00000,529.0,18.000000
29,1030,office supplies,binders,corporate,2376.00000,2292.0,10.978723
30,1031,technology,phones,corporate,6073.00000,-44.0,10.000000
31,1032,office supplies,storage,CORPORATE,7933.00000,-487.0,9.000000
32,1033,TECHNOLOGY,ACCESSORIES,CORPORATE,8817.00000,-65.0,10.000000
33,1034,furniture,tables,HOME OFFICE,3758.00000,126.0,12.000000
34,1035,FURNITURE,CHAIRS,HOME OFFICE,9189.00000,-498.0,20.000000
35,1036,technology,phones,Consumer,819.00000,-42.0,12.000000
36,1037,technology,phones,CORPORATE,1449.00000,486.0,19.000000
37,1038,office supplies,binders,consumer,8462.00000,2842.0,3.000000
38,1039,TECHNOLOGY,ACCESSORIES,CORPORATE,2603.00000,2202.0,16.000000
39,1040,TECHNOLOGY,ACCESSORIES,CORPORATE,4842.00000,1661.0,20.000000
40,1041,office supplies,storage,CORPORATE,9335.00000,2593.0,7.000000
41,1042,furniture,tables,home office,7037.00000,2251.0,12.000000
42,1043,office supplies,storage,HOME OFFICE,5351.06383,-5.0,8.000000
43,1044,FURNITURE,CHAIRS,consumer,6039.00000,-414.0,19.000000
44,1045,TECHNOLOGY,ACCESSORIES,CORPORATE,4108.00000,-471.0,3.000000
45,1046,furniture,tables,corporate,1464.00000,437.0,3.000000
46,1047,office supplies,binders,home office,1660.00000,1605.0,10.978723
47,1048,technology,phones,corporate,8453.00000,377.0,18.000000
48,1049,FURNITURE,CHAIRS,corporate,9855.00000,1860.0,16.000000
49,1050,FURNITURE,CHAIRS,Consumer,7169.00000,279.0,4.000000

In [67]:
df["Category"]=df["Category"].str.strip().str.title()

In [70]:
df["Sub-Category"]=df["Sub-Category"].str.strip().str.title()
df["Segment"]=df["Segment"].str.strip().str.title()

In [71]:
df

,Order ID,Category,Sub-Category,Segment,Sales,Profit,Quantity
0,1001,Furniture,Tables,Consumer,909.00000,2537.0,9.000000
1,1002,Furniture,Chairs,Corporate,2786.00000,2516.0,4.000000
2,1003,Furniture,Tables,Corporate,9435.00000,-144.0,19.000000
3,1004,Office Supplies,Storage,Consumer,988.00000,-117.0,10.978723
4,1005,Furniture,Chairs,Home Office,934.00000,1798.0,7.000000
5,1006,Furniture,Tables,Corporate,9428.00000,1218.0,8.000000
6,1007,Office Supplies,Storage,Home Office,5351.06383,2815.0,1.000000
7,1008,Furniture,Chairs,Corporate,7424.00000,893.0,9.000000
8,1009,Furniture,Chairs,Corporate,6014.00000,-82.0,3.000000
9,1010,Office Supplies,Storage,Consumer,6381.00000,2971.0,12.000000
10,1011,Technology,Accessories,Home Office,1211.00000,2488.0,15.000000
11,1012,Technology,Accessories,Consumer,6701.00000,-178.0,18.000000
12,1013,Technology,Phones,Corporate,6425.00000,1864.0,7.000000
13,1014,Furniture,Tables,Consumer,1250.00000,2208.0,8.000000
14,1015,Technology,Phones,Consumer,4314.00000,-87.0,13.000000
15,1016,Technology,Phones,Consumer,6477.00000,166.0,12.000000
16,1017,Technology,Phones,Corporate,4874.00000,2374.0,3.000000
17,1018,Technology,Accessories,Corporate,3303.00000,1687.0,8.000000
18,1019,Furniture,Chairs,Consumer,6716.00000,605.0,18.000000
19,1020,Furniture,Chairs,Corporate,5813.00000,2952.0,2.000000
20,1021,Furniture,Chairs,Consumer,5668.00000,1143.0,9.000000
21,1022,Office Supplies,Binders,Corporate,9792.00000,2440.0,11.000000
22,1023,Furniture,Chairs,Corporate,8679.00000,1143.0,15.000000
23,1024,Furniture,Chairs,Home Office,2787.00000,510.0,18.000000
24,1025,Technology,Accessories,Home Office,7519.00000,1890.0,13.000000
25,1026,Technology,Phones,Corporate,2766.00000,1587.0,16.000000
26,1027,Office Supplies,Binders,Consumer,2296.00000,1143.0,6.000000
27,1028,Furniture,Tables,Consumer,5351.06383,1143.0,13.000000
28,1029,Technology,Accessories,Consumer,9169.00000,529.0,18.000000
29,1030,Office Supplies,Binders,Corporate,2376.00000,2292.0,10.978723
30,1031,Technology,Phones,Corporate,6073.00000,-44.0,10.000000
31,1032,Office Supplies,Storage,Corporate,7933.00000,-487.0,9.000000
32,1033,Technology,Accessories,Corporate,8817.00000,-65.0,10.000000
33,1034,Furniture,Tables,Home Office,3758.00000,126.0,12.000000
34,1035,Furniture,Chairs,Home Office,9189.00000,-498.0,20.000000
35,1036,Technology,Phones,Consumer,819.00000,-42.0,12.000000
36,1037,Technology,Phones,Corporate,1449.00000,486.0,19.000000
37,1038,Office Supplies,Binders,Consumer,8462.00000,2842.0,3.000000
38,1039,Technology,Accessories,Corporate,2603.00000,2202.0,16.000000
39,1040,Technology,Accessories,Corporate,4842.00000,1661.0,20.000000
40,1041,Office Supplies,Storage,Corporate,9335.00000,2593.0,7.000000
41,1042,Furniture,Tables,Home Office,7037.00000,2251.0,12.000000
42,1043,Office Supplies,Storage,Home Office,5351.06383,-5.0,8.000000
43,1044,Furniture,Chairs,Consumer,6039.00000,-414.0,19.000000
44,1045,Technology,Accessories,Corporate,4108.00000,-471.0,3.000000
45,1046,Furniture,Tables,Corporate,1464.00000,437.0,3.000000
46,1047,Office Supplies,Binders,Home Office,1660.00000,1605.0,10.978723
47,1048,Technology,Phones,Corporate,8453.00000,377.0,18.000000
48,1049,Furniture,Chairs,Corporate,9855.00000,1860.0,16.000000
49,1050,Furniture,Chairs,Consumer,7169.00000,279.0,4.000000