In [43]:
import pandas as pd

In [44]:
df=pd.read_csv("healthcare_dataset1.csv")

In [45]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [52]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(11)
memory usage: 6.4+ MB

In [67]:
df["Date of Admission"]=pd.to_datetime(df["Date of Admission"],errors='coerce')
df["Discharge Date"]=pd.to_datetime(df["Discharge Date"],errors='coerce')

In [68]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Discharge Date,Priority_level
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,2024-04-29,high priority
17421,dErRick hartMAn,39,Male,O+,Arthritis,2023-07-10,Mary Evans,Miller-Dawson,Blue Cross,40445.344641,346,Urgent,2023-07-30,Lipitor,Normal,2023-07-30,high priority
44725,alLEn BOoNE,82,Male,B-,Arthritis,2022-05-21,Trevor Schwartz,Sons and Bryant,UnitedHealthcare,7000.191756,323,Urgent,2022-06-10,Paracetamol,Inconclusive,2022-06-10,high priority
32233,cRysTaL wiLLiAMS,53,Male,A-,Arthritis,2023-05-24,Samantha Reed,Hernandez-Lloyd,Blue Cross,45292.756518,273,Elective,2023-05-29,Lipitor,Abnormal,2023-05-29,planned care
44714,kAThLeeN GoMEZ,28,Male,O+,Arthritis,2019-07-11,Kiara Johnson,Warner and Sons,Aetna,24216.587471,398,Urgent,2019-07-14,Ibuprofen,Inconclusive,2019-07-14,high priority
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20889,KiMBERLY FErgUsoN,30,Female,A-,Obesity,2021-05-02,Logan King,Rivera Sons and,Aetna,30043.678235,383,Emergency,2021-05-13,Aspirin,Inconclusive,2021-05-13,Immediate care
39302,RANdy yOUNG,56,Female,B-,Obesity,2023-09-24,Barry Long,LLC Peterson,Blue Cross,7554.974749,457,Urgent,2023-09-30,Penicillin,Normal,2023-09-30,high priority
5901,iAN MCCLAIn,25,Male,AB-,Obesity,2023-05-26,Amy Anderson,Roth-Benton,UnitedHealthcare,35693.375034,260,Emergency,2023-06-25,Lipitor,Normal,2023-06-25,Immediate care
47577,robERt FoRd,29,Male,B+,Obesity,2021-04-04,Linda Caldwell,Johnson-Johns,UnitedHealthcare,8837.393133,240,Emergency,2021-04-12,Aspirin,Abnormal,2021-04-12,Immediate care
34044,chRIsToPheR fRAnkliN,19,Male,AB+,Obesity,2021-05-19,Juan Ayers,"and Shepard, Garcia Garcia",Cigna,25149.130872,219,Urgent,2021-06-14,Aspirin,Inconclusive,2021-06-14,high priority

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55500 entries, 55499 to 34044
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15   Discharge Date     55500 non-null  datetime64[ns]
 16  Priority_level      55500 non-null  object
dtypes: datetime64[ns](3), float64(1), int64(2), object(11)
memory usage: 7.6+ MB

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 55500 entries, 55499 to 34044
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  datetime64[ns]
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15   Discharge Date     55500 non-null  datetime64[ns]
 16  Priority_level      55500 non-null  object
dtypes: datetime64[ns](3), float64(1), int64(2), object(11)
memory usage: 7.6+ MB

In [73]:
def categorize_urgency(admission):
    if admission=='Emergency':
        return'Immediate care'
    elif admission=='Urgent':
        return'high priority'
    else:
        return'planned care'

df['Priority_level']=df['Admission Type'].apply(categorize_urgency)

In [74]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Discharge Date,Priority_level
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,2024-04-29,high priority
44725,alLEn BOoNE,82,Male,B-,Arthritis,2022-05-21,Trevor Schwartz,Sons and Bryant,UnitedHealthcare,7000.191756,323,Urgent,2022-06-10,Paracetamol,Inconclusive,2022-06-10,high priority
32233,cRysTaL wiLLiAMS,53,Male,A-,Arthritis,2023-05-24,Samantha Reed,Hernandez-Lloyd,Blue Cross,45292.756518,273,Elective,2023-05-29,Lipitor,Abnormal,2023-05-29,planned care
44714,kAThLeeN GoMEZ,28,Male,O+,Arthritis,2019-07-11,Kiara Johnson,Warner and Sons,Aetna,24216.587471,398,Urgent,2019-07-14,Ibuprofen,Inconclusive,2019-07-14,high priority
17410,HeIDI phIlLiPS,78,Female,B-,Arthritis,2024-04-09,Kristie Allen,PLC Beasley,Blue Cross,12129.594068,361,Emergency,2024-04-15,Aspirin,Normal,2024-04-15,Immediate care
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5901,iAN MCCLAIn,25,Male,AB-,Obesity,2023-05-26,Amy Anderson,Roth-Benton,UnitedHealthcare,35693.375034,260,Emergency,2023-06-25,Lipitor,Normal,2023-06-25,Immediate care
20326,LAUrA ROWe,52,Female,O-,Obesity,2021-03-31,Sarah Anderson,Collins-Harris,Aetna,2193.214445,394,Elective,2021-04-07,Lipitor,Inconclusive,2021-04-07,planned care
27593,tIffAnY MurPHY,44,Female,B+,Obesity,2023-12-08,Jeffrey Hernandez,Smith and Sons,Aetna,16636.163846,226,Elective,2024-01-07,Penicillin,Normal,2024-01-07,planned care
39369,TiFFAnY BoOtH,19,Female,O+,Obesity,2022-09-30,Christopher Wang,"and Villa Maddox Hall,",Cigna,27993.894097,120,Elective,2022-10-02,Aspirin,Abnormal,2022-10-02,planned care
34044,chRIsToPheR fRAnkliN,19,Male,AB+,Obesity,2021-05-19,Juan Ayers,"and Shepard, Garcia Garcia",Cigna,25149.130872,219,Urgent,2021-06-14,Aspirin,Inconclusive,2021-06-14,high priority

In [75]:
#to find the hospital stay days we have to subtract Discharde date and Date of Admission
df["Hospital stay days"]=(df["Discharge Date"]-df["Date of Admission"]).dt.days

In [76]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Discharge Date,Priority_level,Hospital stay days
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal,2024-04-29,high priority,27
44725,alLEn BOoNE,82,Male,B-,Arthritis,2022-05-21,Trevor Schwartz,Sons and Bryant,UnitedHealthcare,7000.191756,323,Urgent,2022-06-10,Paracetamol,Inconclusive,2022-06-10,high priority,20
32233,cRysTaL wiLLiAMS,53,Male,A-,Arthritis,2023-05-24,Samantha Reed,Hernandez-Lloyd,Blue Cross,45292.756518,273,Elective,2023-05-29,Lipitor,Abnormal,2023-05-29,planned care,5
44714,kAThLeeN GoMEZ,28,Male,O+,Arthritis,2019-07-11,Kiara Johnson,Warner and Sons,Aetna,24216.587471,398,Urgent,2019-07-14,Ibuprofen,Inconclusive,2019-07-14,high priority,3
17410,HeIDI phIlLiPS,78,Female,B-,Arthritis,2024-04-09,Kristie Allen,PLC Beasley,Blue Cross,12129.594068,361,Emergency,2024-04-15,Aspirin,Normal,2024-04-15,Immediate care,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5901,iAN MCCLAIn,25,Male,AB-,Obesity,2023-05-26,Amy Anderson,Roth-Benton,UnitedHealthcare,35693.375034,260,Emergency,2023-06-25,Lipitor,Normal,2023-06-25,Immediate care,30
20326,LAUrA ROWe,52,Female,O-,Obesity,2021-03-31,Sarah Anderson,Collins-Harris,Aetna,2193.214445,394,Elective,2021-04-07,Lipitor,Inconclusive,2021-04-07,planned care,7
27593,tIffAnY MurPHY,44,Female,B+,Obesity,2023-12-08,Jeffrey Hernandez,Smith and Sons,Aetna,16636.163846,226,Elective,2024-01-07,Penicillin,Normal,2024-01-07,planned care,30
39369,TiFFAnY BoOtH,19,Female,O+,Obesity,2022-09-30,Christopher Wang,"and Villa Maddox Hall,",Cigna,27993.894097,120,Elective,2022-10-02,Aspirin,Abnormal,2022-10-02,planned care,2
34044,chRIsToPheR fRAnkliN,19,Male,AB+,Obesity,2021-05-19,Juan Ayers,"and Shepard, Garcia Garcia",Cigna,25149.130872,219,Urgent,2021-06-14,Aspirin,Inconclusive,2021-06-14,high priority,26

In [78]:
#we are taking the group Medical Condition to find the age 
df.groupby("Medical Condition")["Age"].mean()

Medical Condition
Arthritis       51.565320
Asthma          51.575830
Cancer          51.558795
Diabetes        51.554170
Hypertension    51.741915
Obesity         51.240277
Name: Age, dtype: float64

In [79]:
df.groupby("Medical Condition")["Hospital stay days"].mean()

Medical Condition
Arthritis       15.517404
Asthma          15.696570
Cancer          15.495827
Diabetes        15.422936
Hypertension    15.458626
Obesity         15.464305
Name: Hospital stay days, dtype: float64

In [81]:
df.groupby("Medical Condition")["Billing Amount"].mean()

Medical Condition
Arthritis       25497.327056
Asthma          25635.249359
Cancer          25161.792707
Diabetes        25638.405577
Hypertension    25497.095761
Obesity         25805.971259
Name: Billing Amount, dtype: float64

In [85]:
df.groupby("Admission Type")["Billing Amount"].mean()

Admission Type
Elective     25602.226311
Emergency    25497.397157
Urgent       25517.364497
Name: Billing Amount, dtype: float64

In [86]:
df.groupby("Priority_level")["Hospital stay days"].mean()

Priority_level
Immediate care    15.595052
high priority     15.408000
planned care      15.525328
Name: Hospital stay days, dtype: float64

In [87]:
print(pd.crosstab(
    df["Medical Condition"],
    df["Gender"]
))

Gender             Female  Male
Medical Condition
Arthritis            4686  4622
Asthma               4553  4632
Cancer               4602  4625
Diabetes             4651  4653
Hypertension         4612  4633
Obesity              4622  4609